name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: aarch64-linux-musl
            host: x86_64-linux
          - os: ubuntu-22.04
            target: x86_64-linux-musl
            host: x86_64-linux
          - os: ubuntu-22.04
            target: mips-linux-musl
            host: x86_64-linux
          - os: ubuntu-22.04
            target: mips-linux-muslsf
            host: x86_64-linux
          - os: ubuntu-22.04
            target: mipsel-linux-musl
            host: x86_64-linux
          - os: ubuntu-22.04
            target: mipsel-linux-muslsf
            host: x86_64-linux
          - os: ubuntu-22.04-arm
            target: aarch64-linux-musl
            host: aarch64-linux
          - os: ubuntu-22.04-arm
            target: x86_64-linux-musl
            host: aarch64-linux
          - os: ubuntu-22.04-arm
            target: mips-linux-musl
            host: aarch64-linux
          - os: ubuntu-22.04-arm
            target: mips-linux-muslsf
            host: aarch64-linux
          - os: ubuntu-22.04-arm
            target: mipsel-linux-musl
            host: aarch64-linux
          - os: ubuntu-22.04-arm
            target: mipsel-linux-muslsf
            host: aarch64-linux
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}-cross-${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: richfelker/musl-cross-make
      - run: |
          cat << EOF > config.mak
          TARGET = ${{ matrix.target }}
          OUTPUT = ${{ github.workspace }}/output/${{ matrix.target }}-cross-${{ matrix.host }}
          COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"
          MUSL_VER = 1.2.5
          EOF
      - run: make install -j4
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-cross-${{ matrix.host }}
          path: output/*
          retention-days: 5
