name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild:
    strategy:
      matrix:
        target:
          - aarch64-linux-musl
          - mips-linux-musl
          - mips-linux-muslsf
          - mipsel-linux-musl
          - mipsel-linux-muslsf
          - x86_64-linux-musl
        host:
          - aarch64-linux
          - x86_64-linux
        include:
          - host: aarch64-linux
            os: ubuntu-22.04-arm
          - host: x86_64-linux
            os: ubuntu-22.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}-cross-${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: richfelker/musl-cross-make
      - run: |
          cat << EOF > config.mak
          TARGET = ${{ matrix.target }}
          HOST = ${{ matrix.host }}
          OUTPUT = ${{ github.workspace }}/output/${{ matrix.target }}-cross-${{ matrix.host }}
          COMMON_CONFIG += CFLAGS="-g0 -Os" CXXFLAGS="-g0 -Os" LDFLAGS="-s"
          MUSL_VER = 1.2.5
          EOF
      - run: make install -j4
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-cross-${{ matrix.host }}
          path: output/*
          retention-days: 5
